import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { getBuildIdentity } from "../../src/data/buildIdentity.ts";
import { createBuildQueueItem,getBuildQueueView } from "../../src/data/buildQueue.ts";
import { createCaptureDraftReceipt } from "../../src/data/captureDraft.ts";
import { createCaptureTriageItem,getCaptureTriageView } from "../../src/data/captureTriage.ts";
import { createEvidenceBundle } from "../../src/data/evidenceBundle.ts";
import { FLOCK_RELAY_SNAPSHOT,getFlockRelayView } from "../../src/data/flockRelaySnapshot.ts";
import { PROJECT_COCKPIT_SNAPSHOT,getProjectCockpitView } from "../../src/data/projectCockpit.ts";
import { PROMOTION_EVIDENCE_MAX_AGE_DAYS,getPromotionReadinessView } from "../../src/data/promotionReadiness.ts";
const SHA="a".repeat(40),TIME="2026-07-29T20:00:00.000Z",DAY=86_400_000;
function bundle(buildSha=SHA){const at=new Date(TIME),receipt=createCaptureDraftReceipt("Safe promotion metadata",new Date("2026-07-29T19:40:00.000Z"));assert.equal(receipt.ok,true);if(!receipt.ok)throw new Error("receipt");return createEvidenceBundle({sourcePath:"docs/flock/packets/F_DINK_EVIDENCE_BUNDLE_BOUNDARY_20260729_C10_B.md",sourceSha:"595dcef7dbbe3a3c42091e665af284cfb6e0d665",observedAt:TIME,createdAt:at,buildIdentity:getBuildIdentity(buildSha),cockpit:getProjectCockpitView(PROJECT_COCKPIT_SNAPSHOT,at),buildQueue:getBuildQueueView([createBuildQueueItem({id:"build-promotion-readiness",title:"Review promotion readiness evidence",area:"Cloud proof",priority:"P0",createdAt:"2026-07-29T19:30:00.000Z"})]),captureTriage:getCaptureTriageView([createCaptureTriageItem({receipt:receipt.receipt,category:"BUILD",priority:"NOW"})]),relay:getFlockRelayView(FLOCK_RELAY_SNAPSHOT,at)});}
function view(options={}){return getPromotionReadinessView({evidenceBundle:bundle(),buildIdentity:getBuildIdentity(SHA),now:new Date(Date.parse(TIME)+1000),...options});}
test("matching fresh evidence is advisory ready but human approval stays pending",()=>{const result=view();assert.equal(result.state,"READY_FOR_HUMAN_REVIEW");assert.equal(result.approvalState,"PENDING_HUMAN_GATE");assert.deepEqual(result.reasonCodes,["HUMAN_APPROVAL_REQUIRED"]);assert.deepEqual(result.criteria.map(x=>x.state),["PASS","PASS","PASS","PASS","PASS","PENDING"]);assert.ok(Object.isFrozen(result));assert.ok(Object.values(result.effectFlags).every(x=>x===false));});
test("freshness and hostile inputs fail closed with stable reasons",()=>{assert.equal(PROMOTION_EVIDENCE_MAX_AGE_DAYS,7);assert.equal(view({now:new Date(Date.parse(TIME)+7*DAY)}).state,"READY_FOR_HUMAN_REVIEW");assert.ok(view({now:new Date(Date.parse(TIME)+7*DAY+1)}).reasonCodes.includes("EVIDENCE_STALE"));assert.ok(view({buildIdentity:getBuildIdentity("b".repeat(40))}).reasonCodes.includes("BUILD_SHA_MISMATCH"));assert.ok(view({buildIdentity:getBuildIdentity(undefined)}).reasonCodes.includes("CURRENT_BUILD_UNBOUND"));const hostile={...structuredClone(bundle()),raw:"unknown"};assert.ok(view({evidenceBundle:hostile}).reasonCodes.includes("EVIDENCE_BOUNDARY_INVALID"));const elevated=structuredClone(bundle());elevated.effectFlags.deployed=true;const bad=view({evidenceBundle:elevated});assert.ok(bad.reasonCodes.includes("EVIDENCE_EFFECT_CLAIM"));assert.equal(bad.state,"PENDING_HUMAN_GATE");});
test("promotion card is read-only, explicit, accessible, and narrow-screen safe",async()=>{const source=await readFile(new URL("../../src/components/PromotionReadinessCard.tsx",import.meta.url),"utf8");for(const literal of ["PROMOTION READINESS","READY FOR HUMAN REVIEW","NOT READY FOR HUMAN REVIEW","HUMAN GATE REQUIRED","No approval has been recorded.","No merge, deployment, delivery, or canon promotion occurred.","NO EVIDENCE REASONS","BLOCKED","STALE EVIDENCE","EVIDENCE MISMATCH"])assert.ok(source.includes(literal));assert.match(source,/accessibilityRole=["']header["']/);assert.match(source,/accessibilityLiveRegion=["']polite["']/);assert.match(source,/width:\s*["']100%["']/);assert.match(source,/minWidth:\s*0/);assert.doesNotMatch(source,/\b(Pressable|Button|TouchableOpacity|Clipboard|Share|Linking|fetch|AsyncStorage|FileSystem)\b/);});
