import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { C7_C12_CHECKPOINTS,createConsolidatedCycleReceipt } from "../../src/data/consolidatedCycleReceipt.ts";
import { getResilienceFreshnessView } from "../../src/data/resilienceFreshness.ts";
const DAY=86_400_000,OBSERVED="2026-07-29T16:00:00.000Z",NOW=new Date("2026-07-29T22:00:00.000Z"),C12="a56cd9daff46fdbb3477fa38de1dd3e307d00f31";
const C12_FILES=[
["docs/flock/packets/F_DINK_RESILIENCE_FRESHNESS_MODEL_20260729_C12_A.md","c33bbae4c82f23694df5e16252a631a05169222a"],["docs/flock/packets/F_DINK_CONSOLIDATED_RECEIPT_MODEL_20260729_C12_B.md","b78439361bf882f3200464a8d44c11049734779c"],["docs/flock/packets/F_CURSOR_ENDER_RESILIENCE_POLISH_20260729_C12_A.md","3a89d85153f8631ad2e915e09614442503fdaf9e"],["docs/flock/packets/F_CURSOR_ENDER_RECEIPT_TIMELINE_20260729_C12_B.md","fc331bab42f275e51dce8ed94125f99cf110a88a"],["docs/flock/packets/F_BEAN_THUFIR_RESILIENCE_REGRESSION_20260729_C12_A.md","7ac677d89b824fa3585d8f76903baae2e46b80c3"],["docs/flock/packets/F_BEAN_THUFIR_FINAL_SOURCE_AUDIT_20260729_C12_B.md","01a58b9d1716f644eb3541b20953e9d088e7203b"]];
function receipt(cycles=C7_C12_CHECKPOINTS){return createConsolidatedCycleReceipt({sourcePath:"docs/flock/packets/F_DINK_CONSOLIDATED_RECEIPT_MODEL_20260729_C12_B.md",sourceSha:C12,createdAt:NOW,cycles});}
test("C12 exposes six separate immutable Aeye packet files",()=>{for(const [path,sha] of C12_FILES){assert.equal(execFileSync("git",["rev-parse",C12+":"+path],{encoding:"utf8"}).trim(),sha);}});
test("C7 remains legacy-bundled while C8-C12 list six separate packets",()=>{assert.deepEqual(C7_C12_CHECKPOINTS.map(x=>x.packetIds.length),[3,6,6,6,6,6]);assert.ok(C7_C12_CHECKPOINTS.every(x=>x.verificationState==="UNVERIFIED"));const result=receipt([...C7_C12_CHECKPOINTS].reverse());assert.deepEqual(result.cycles.map(x=>x.cycle),["C7","C8","C9","C10","C11","C12"]);assert.equal(result.summaryState,"PARTIAL_OR_UNVERIFIED");assert.deepEqual([result.verifiedCycles,result.unverifiedCycles],[0,6]);assert.ok(Object.values(result.effectFlags).every(x=>x===false));});
test("successful run evidence is required and partial or failed cycles cannot inflate",()=>{const base=C7_C12_CHECKPOINTS[1];assert.throws(()=>receipt([{...base,verificationState:"VERIFIED"}]),/verified|run|evidence/i);assert.throws(()=>receipt([{...base,verificationState:"PARTIAL",verificationRunId:44,verificationRunConclusion:"success"}]),/partial|success|evidence/i);const failed=receipt([{...base,verificationState:"FAILED",verificationRunId:44,verificationRunConclusion:"failure"}]);assert.equal(failed.summaryState,"FAILED_EVIDENCE");assert.equal(failed.verifiedCycles,0);assert.throws(()=>createConsolidatedCycleReceipt({sourcePath:"../receipt.md",sourceSha:C12,createdAt:NOW,cycles:[]}),/path/i);});
test("freshness uses injected time and exact millisecond boundaries",()=>{const evaluate=(subject,age)=>getResilienceFreshnessView({subject,observedAt:OBSERVED,now:new Date(Date.parse(OBSERVED)+age)});assert.deepEqual([evaluate("EVIDENCE_BUNDLE",2*DAY).state,evaluate("EVIDENCE_BUNDLE",2*DAY+1).state,evaluate("EVIDENCE_BUNDLE",7*DAY).state,evaluate("EVIDENCE_BUNDLE",7*DAY+1).state],["CURRENT","AGING","AGING","STALE"]);assert.deepEqual([evaluate("PROMOTION_READINESS",DAY).state,evaluate("PROMOTION_READINESS",DAY+1).state],["CURRENT","AGING"]);for(const v of [getResilienceFreshnessView({subject:"EVIDENCE_BUNDLE",observedAt:null,now:NOW}),getResilienceFreshnessView({subject:"EVIDENCE_BUNDLE",observedAt:"bad",now:NOW}),getResilienceFreshnessView({subject:"EVIDENCE_BUNDLE",observedAt:new Date(NOW.getTime()+1).toISOString(),now:NOW})]){assert.equal(v.live,false);assert.equal(v.ageMilliseconds,null);}});
test("receipt timeline is explicit, read-only, accessible, and narrow-screen safe",async()=>{const source=await readFile(new URL("../../src/components/ReceiptTimelineCard.tsx",import.meta.url),"utf8");for(const literal of ["C7–C12 RECEIPT TIMELINE","RECEIPT EVIDENCE · READ ONLY","VERIFIED","PARTIAL","FAILED","UNVERIFIED","CURRENT","AGING","STALE","UNAVAILABLE","INVALID","FUTURE","ALL_CYCLES_EVIDENCE_VERIFIED","PARTIAL_OR_UNVERIFIED","FAILED_EVIDENCE","EMPTY","NO RECEIPT EVIDENCE","LOADING RECEIPT EVIDENCE","RECEIPT EVIDENCE UNAVAILABLE","No merge, deployment, delivery, hosting, or canon promotion is proven."])assert.ok(source.includes(literal),literal);assert.match(source,/accessibilityRole=["']header["']/);assert.match(source,/accessibilityLiveRegion=["']polite["']/);assert.match(source,/width:\s*["']100%["']/);assert.match(source,/minWidth:\s*0/);assert.doesNotMatch(source,/\b(Pressable|Button|TouchableOpacity|Clipboard|Share|Linking|fetch|AsyncStorage|FileSystem)\b/);});
