import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { getBuildIdentity } from "../../src/data/buildIdentity.ts";
import { createFieldBriefSession, reviewFieldBriefItem } from "../../src/data/fieldBrief.ts";
import { advanceShiftHandoffFocus, createShiftHandoffSession, getShiftHandoffView, resetShiftHandoffSession, reviewShiftHandoffItem } from "../../src/data/shiftHandoff.ts";

const NOW=new Date("2026-07-29T20:00:00.000Z"),SHA="a".repeat(40),OTHER_SHA="b".repeat(40);
const EFFECTS=Object.freeze({persisted:false,sent:false,shared:false,copied:false,executed:false,approved:false,merged:false,deployed:false,delivered:false,hosted:false,canonWritten:false,sourceMutated:false});
const EFFECT_KEYS=Object.keys(EFFECTS).sort();
function fieldItem(input){return Object.freeze({...input,truth:"FIELD_BRIEF_ITEM_ADVISORY_NOT_EXECUTED",persistence:"SESSION_ONLY",transport:"NONE",effectFlags:EFFECTS});}
const FIELD_ITEMS=Object.freeze([
 fieldItem({id:"brief-mission-build-one",sourceKind:"DAILY_MISSION",sourceId:"mission-build-one",section:"NOW",rank:1,title:"Review alpha field item",reasonCode:"DAILY_NOW"}),
 fieldItem({id:"brief-mission-build-two",sourceKind:"DAILY_MISSION",sourceId:"mission-build-two",section:"NOW",rank:2,title:"Review beta field item",reasonCode:"DAILY_NOW"}),
 fieldItem({id:"brief-mission-cockpit-plan",sourceKind:"DAILY_MISSION",sourceId:"mission-cockpit-plan",section:"NEXT",rank:3,title:"Plan the next bounded slice",reasonCode:"DAILY_NEXT"}),
 fieldItem({id:"brief-mission-watch-promotion",sourceKind:"PROMOTION_READINESS",sourceId:"mission-watch-promotion",section:"WATCH",rank:4,title:"Complete the separate human promotion gate",reasonCode:"DAILY_WATCH"}),
 fieldItem({id:"brief-gate-promotion",sourceKind:"PROMOTION_READINESS",sourceId:"promotion-readiness",section:"GATE",rank:5,title:"Human promotion decision remains separate",reasonCode:"HUMAN_GATE"})
]);
const FIELD=Object.freeze({truth:"FIELD_BRIEF_ADVISORY_NOT_LIVE",live:false,createdAt:NOW.toISOString(),identityKey:"field-brief|c15-fixture",state:"READY",buildSha:SHA,evidenceObservedAt:"2026-07-29T19:00:00.000Z",blockReasonCodes:Object.freeze([]),now:Object.freeze(FIELD_ITEMS.filter(x=>x.section==="NOW")),next:Object.freeze(FIELD_ITEMS.filter(x=>x.section==="NEXT")),watch:Object.freeze(FIELD_ITEMS.filter(x=>x.section==="WATCH")),gate:Object.freeze(FIELD_ITEMS.filter(x=>x.section==="GATE")),allItems:FIELD_ITEMS,effectFlags:EFFECTS});
const FIELD_SESSION_0=createFieldBriefSession(FIELD),FIELD_SESSION_1=reviewFieldBriefItem(FIELD,FIELD_SESSION_0,FIELD.allItems[0].id),FIELD_SESSION=reviewFieldBriefItem(FIELD,FIELD_SESSION_1,FIELD.allItems[2].id);
const BUILD=getBuildIdentity(SHA);
const input=(overrides={})=>({fieldBrief:FIELD,fieldBriefSession:FIELD_SESSION,buildIdentity:BUILD,now:NOW,...overrides});
const handoff=(overrides={})=>getShiftHandoffView(input(overrides));
function replaceFieldItem(patch,index=0,source=FIELD){const changed=Object.freeze({...source.allItems[index],...patch}),allItems=source.allItems.map((item,i)=>i===index?changed:item);return Object.freeze({...source,now:Object.freeze(allItems.filter(x=>x.section==="NOW")),next:Object.freeze(allItems.filter(x=>x.section==="NEXT")),watch:Object.freeze(allItems.filter(x=>x.section==="WATCH")),gate:Object.freeze(allItems.filter(x=>x.section==="GATE")),allItems:Object.freeze(allItems)});}
function zero(value){assert.deepEqual(Object.keys(value).sort(),EFFECT_KEYS);assert.ok(Object.values(value).every(x=>x===false));}
function blocked(view,codes,{empty=false}={}){assert.equal(view.state,"BLOCKED");assert.deepEqual(view.blockReasonCodes,codes);assert.deepEqual(view.reviewed,[]);assert.deepEqual(view.remaining,[]);assert.deepEqual(view.nextFocus,[]);if(empty)assert.deepEqual(view.allItems,[]);zero(view.effectFlags);}

test("shift handoff is exact, deterministic, bounded, frozen, and identity-bound",()=>{
 const a=handoff(),b=handoff();assert.deepEqual(a,b);assert.equal(a.state,"READY");assert.equal(a.createdAt,NOW.toISOString());assert.equal(a.buildSha,SHA);assert.equal(a.fieldBriefIdentityKey,FIELD.identityKey);assert.equal(a.fieldBriefSessionIdentityKey,FIELD_SESSION.viewIdentityKey);assert.equal(a.identityKey,"shift-handoff|"+NOW.toISOString()+"|"+SHA+"|"+FIELD.identityKey+"|"+FIELD_SESSION.reviewedItemIds.join(",")+"|"+FIELD_SESSION.focusedItemId);assert.deepEqual(a.blockReasonCodes,[]);
 assert.deepEqual(a.reviewed.map(x=>[x.sourceId,x.section,x.rank]),[[FIELD.allItems[0].id,"REVIEWED",1],[FIELD.allItems[2].id,"REVIEWED",2]]);assert.deepEqual(a.remaining.map(x=>[x.sourceId,x.section,x.rank]),[[FIELD.allItems[1].id,"REMAINING",3],[FIELD.allItems[3].id,"REMAINING",4]]);assert.deepEqual(a.nextFocus.map(x=>[x.sourceId,x.section,x.rank]),[[FIELD.allItems[1].id,"NEXT_FOCUS",5]]);assert.deepEqual(a.gate.map(x=>[x.id,x.sourceId,x.section,x.rank]),[["handoff-gate",FIELD.allItems[4].id,"GATE",6]]);assert.deepEqual(a.allItems,[...a.reviewed,...a.remaining,...a.nextFocus,...a.gate]);
 assert.ok(a.reviewed.length<=3&&a.remaining.length<=3&&a.nextFocus.length<=1&&a.gate.length<=1);for(const value of [a,a.reviewed,a.remaining,a.nextFocus,a.gate,a.allItems,a.blockReasonCodes,a.effectFlags])assert.ok(Object.isFrozen(value));for(const item of a.allItems){assert.equal(item.truth,"SHIFT_HANDOFF_ITEM_NOT_SENT_OR_EXECUTED");assert.equal(item.persistence,"SESSION_ONLY");assert.equal(item.transport,"NONE");zero(item.effectFlags);assert.ok(Object.isFrozen(item));}
});

test("clock, Field Brief, session, and build blocks retain canonical order",()=>{
 const drift=handoff({now:new Date(NOW.getTime()+1)});blocked(drift,["INVALID_CHECK_TIME"]);assert.equal(drift.gate.length,1);
 const invalid=handoff({now:new Date("bad")});assert.equal(invalid.createdAt,null);assert.equal(invalid.identityKey,"shift-handoff|invalid");blocked(invalid,["INVALID_CHECK_TIME"],{empty:true});
 const mismatch=handoff({fieldBriefSession:{...FIELD_SESSION,viewIdentityKey:"field-brief|other"}});blocked(mismatch,["SESSION_IDENTITY_MISMATCH"]);assert.equal(mismatch.gate.length,1);
 const badSession=handoff({fieldBriefSession:{...FIELD_SESSION,reviewedItemIds:Object.freeze([FIELD.allItems[0].id,FIELD.allItems[0].id])}});blocked(badSession,["SESSION_STATE_INVALID"]);assert.equal(badSession.gate.length,1);
 const unbound=handoff({buildIdentity:getBuildIdentity(undefined)});blocked(unbound,["BUILD_IDENTITY_UNBOUND"]);assert.equal(unbound.gate.length,1);
 const wrongBuild=handoff({buildIdentity:getBuildIdentity(OTHER_SHA)});blocked(wrongBuild,["BUILD_IDENTITY_MISMATCH"]);assert.equal(wrongBuild.gate.length,1);
 const kept=Object.freeze([...FIELD.watch,...FIELD.gate].map((x,i)=>Object.freeze({...x,rank:i+1,effectFlags:EFFECTS}))),bf=Object.freeze({...FIELD,identityKey:"field-brief|blocked",state:"BLOCKED",blockReasonCodes:Object.freeze(["STALE_EVIDENCE"]),now:Object.freeze([]),next:Object.freeze([]),watch:Object.freeze(kept.filter(x=>x.section==="WATCH")),gate:Object.freeze(kept.filter(x=>x.section==="GATE")),allItems:kept});
 const compound=handoff({fieldBrief:bf,buildIdentity:getBuildIdentity(undefined)});blocked(compound,["FIELD_BRIEF_BLOCKED","SESSION_IDENTITY_MISMATCH","SESSION_STATE_INVALID","BUILD_IDENTITY_UNBOUND"]);assert.deepEqual(compound.allItems,compound.gate);assert.equal(compound.gate[0]?.rank,1);
});

test("schema, secret, duplicate, and effect claims fail closed without echo",()=>{
 blocked(getShiftHandoffView({fieldBrief:FIELD,fieldBriefSession:FIELD_SESSION,buildIdentity:BUILD}),["INPUT_SCHEMA_INVALID"],{empty:true});
 const raw=getShiftHandoffView({...input(),rawCapture:"password=hunter2"});blocked(raw,["INPUT_SCHEMA_INVALID"],{empty:true});assert.equal(JSON.stringify(raw).includes("hunter2"),false);
 for(const title of ["password=hunter2","Authorization: Bearer abcdefghijklmnop","github_pat_"+"a".repeat(24),"Merged and deployed release"]){const view=handoff({fieldBrief:replaceFieldItem({title})});blocked(view,["INPUT_SCHEMA_INVALID"],{empty:true});assert.equal(JSON.stringify(view).includes(title),false);}
 const claimed=handoff({fieldBrief:{...FIELD,effectFlags:{...FIELD.effectFlags,sent:true}}});blocked(claimed,["INPUT_EFFECT_CLAIM"],{empty:true});assert.equal(JSON.stringify(claimed).includes('"sent":true'),false);
 const duplicate=replaceFieldItem({id:FIELD.allItems[0].id},1);blocked(handoff({fieldBrief:duplicate}),["DUPLICATE_SOURCE_ID"],{empty:true});
});

test("derived ID domains stay collision-safe",()=>{const f=replaceFieldItem({id:"handoff-gate"}),s0=createFieldBriefSession(f),s1=reviewFieldBriefItem(f,s0,f.allItems[0].id),s=reviewFieldBriefItem(f,s1,f.allItems[2].id),v=handoff({fieldBrief:f,fieldBriefSession:s});assert.equal(v.state,"READY");assert.equal(new Set(v.allItems.map(x=>x.id)).size,v.allItems.length);assert.ok(v.allItems.some(x=>x.id==="handoff-reviewed-handoff-gate"));assert.ok(v.allItems.some(x=>x.id==="handoff-gate"));});

test("handoff session is frozen, idempotent, resettable, view-bound, and source-preserving",()=>{
 const before=JSON.stringify(input()),view=handoff(),initial=createShiftHandoffSession(view);assert.equal(initial.focusedHandoffItemId,view.allItems[0].id);assert.deepEqual(initial.reviewedHandoffItemIds,[]);zero(initial.effectFlags);const advanced=advanceShiftHandoffFocus(view,initial);assert.equal(advanced.focusedHandoffItemId,view.allItems[1].id);let wrapped=initial;for(let i=0;i<view.allItems.length;i+=1)wrapped=advanceShiftHandoffFocus(view,wrapped);assert.equal(wrapped.focusedHandoffItemId,initial.focusedHandoffItemId);
 const second=reviewShiftHandoffItem(view,initial,view.allItems[1].id),canonical=reviewShiftHandoffItem(view,second,view.allItems[0].id);assert.deepEqual(canonical.reviewedHandoffItemIds,[view.allItems[0].id,view.allItems[1].id]);assert.deepEqual(reviewShiftHandoffItem(view,canonical,view.allItems[0].id),canonical);const all=view.allItems.reduce((s,x)=>reviewShiftHandoffItem(view,s,x.id),initial);assert.equal(all.focusedHandoffItemId,null);assert.deepEqual(resetShiftHandoffSession(view),createShiftHandoffSession(view));assert.throws(()=>reviewShiftHandoffItem(view,initial,"handoff-unknown"),/handoff|item|found/i);assert.throws(()=>advanceShiftHandoffFocus(view,{...initial,viewIdentityKey:"forged"}),/identity|mismatch/i);assert.equal(JSON.stringify(input()),before);
});

test("Shift Handoff UI is ordered, explicit, accessible, narrow-screen safe, and offline-only",async()=>{
 const [source,home,pkgText,workflow]=await Promise.all([readFile(new URL("../../src/components/ShiftHandoffCard.tsx",import.meta.url),"utf8"),readFile(new URL("../../app/index.tsx",import.meta.url),"utf8"),readFile(new URL("../../package.json",import.meta.url),"utf8"),readFile(new URL("../../.github/workflows/verify.yml",import.meta.url),"utf8")]);
 for(const literal of ["SHIFT HANDOFF","shift-handoff-card","READY · DRAFT NOT SENT","BLOCKED · DRAFT NOT SENT","REVIEWED","REMAINING","NEXT FOCUS","GATE","NO REVIEWED HANDOFF ITEMS","NO REMAINING HANDOFF ITEMS","NO NEXT FOCUS HANDOFF ITEM","NO GATE HANDOFF ITEM","HUMAN GATE REQUIRED","SESSION REVIEWED · NOT SENT OR EXECUTED","NOT REVIEWED · NOT SENT OR EXECUTED","SESSION FOCUS · NOT SEND OR EXECUTION","Review handoff item","Focus next handoff item","INVALID_CHECK_TIME","INPUT_SCHEMA_INVALID","INPUT_EFFECT_CLAIM","DUPLICATE_SOURCE_ID","FIELD_BRIEF_BLOCKED","SESSION_IDENTITY_MISMATCH","SESSION_STATE_INVALID","BUILD_IDENTITY_UNBOUND","BUILD_IDENTITY_MISMATCH","Handoff and source clocks do not match.","Source metadata shape is invalid.","Source metadata claims a forbidden effect.","Source IDs are not unique.","Field Brief is blocked.","Field Brief session identity does not match.","Field Brief session state is invalid.","Build identity is not CI-bound.","Build and Field Brief SHAs do not match.","Draft metadata only. No handoff was saved, sent, shared, copied, approved, executed, merged, deployed, delivered, hosted, or promoted to canon."])assert.ok(source.includes(literal),literal);
 assert.ok(source.indexOf("REVIEWED")<source.indexOf("REMAINING")&&source.indexOf("REMAINING")<source.indexOf("NEXT FOCUS")&&source.indexOf("NEXT FOCUS")<source.indexOf("GATE"));assert.match(source,/testID=["']shift-handoff-card["']/);assert.match(source,/accessibilityRole=["']header["']/);assert.match(source,/accessibilityLiveRegion=["']polite["']/);assert.match(source,/accessibilityRole=["']button["']/);assert.match(source,/accessibilityState=/);assert.match(source,/accessibilityHint=/);assert.match(source,/session-only/i);assert.match(source,/does not send[,\s]+execute[,\s]+or change inputs/i);assert.match(source,/\bselectable\b/);assert.match(source,/onReview/);assert.match(source,/onAdvanceFocus/);assert.match(source,/minHeight:\s*48/);assert.match(source,/width:\s*["']100%["']/);assert.match(source,/minWidth:\s*0/);assert.match(source,/flexWrap:\s*["']wrap["']/);assert.doesNotMatch(source,/allowFontScaling=\{false\}|numberOfLines=|horizontal=\{true\}/);assert.doesNotMatch(source,/\b(Clipboard|Share|Linking|fetch|XMLHttpRequest|WebSocket|AsyncStorage|FileSystem|localStorage|sessionStorage|indexedDB|openURL|useRouter)\b|router\.push|href=|expo-(?:sharing|clipboard|file-system)/);
 const d=home.indexOf("<DailyMissionCard"),f=home.indexOf("<FieldBriefCard"),h=home.indexOf("<ShiftHandoffCard"),c=home.indexOf("<CommandBoard");assert.ok(d>=0&&f>d&&h>f&&c>h);const script=JSON.parse(pkgText).scripts["test:contracts"],matches=script.match(/tests\/contracts\/shift-handoff\.test\.mjs/g)??[];assert.equal(matches.length,1);assert.ok(workflow.indexOf("Run behavior contracts")<workflow.indexOf("Typecheck"));assert.ok(workflow.indexOf("Typecheck")<workflow.indexOf("Export Android bundle"));
});
