import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { BUILD_QUEUE_PRIORITIES, type BuildQueuePriority, type BuildQueueView } from "../data/buildQueue";

const PRIORITY_LABELS: Readonly<Record<BuildQueuePriority, string>> = Object.freeze({ P0: "P0 · NOW", P1: "P1 · NEXT", P2: "P2 · LATER", P3: "P3 · PARKED" });
type Props = Readonly<{ queue: BuildQueueView; variant: "home" | "build"; onAdd: (title: string, priority: BuildQueuePriority) => void; onReprioritize: (id: string, priority: BuildQueuePriority) => void; onAdvance: (id: string) => void }>;

function PriorityButton({ id, priority, selected, onSelect }: Readonly<{ id: string; priority: BuildQueuePriority; selected: boolean; onSelect: (priority: BuildQueuePriority) => void }>) {
  return <Pressable accessibilityHint="Changes session-only priority. Does not save or dispatch." accessibilityLabel={`Set ${id} priority to ${PRIORITY_LABELS[priority]}`} accessibilityRole="button" accessibilityState={{ selected }} onPress={() => onSelect(priority)} style={({pressed}) => [styles.priorityButton, selected && styles.prioritySelected, pressed && styles.pressed]}><Text selectable style={[styles.priorityText, selected && styles.priorityTextSelected]}>{PRIORITY_LABELS[priority]}</Text></Pressable>;
}

export function BuildQueueCard({ queue, variant, onAdd, onReprioritize, onAdvance }: Props) {
  const [draft,setDraft]=useState(""); const [priority,setPriority]=useState<BuildQueuePriority>("P1");
  const visible = variant === "home" ? queue.items.slice(0,3) : queue.items;
  const addDisabled = draft.trim() === "";
  const addMove = () => { const title=draft.trim(); if (title === "") return; onAdd(title,priority); setDraft(""); };
  return <View style={styles.container} testID="build-queue-card">
    <View style={styles.heading}><Text selectable style={styles.eyebrow}>{variant === "home" ? "RIGHT NOW" : "BUILD QUEUE"}</Text><Text accessibilityRole="header" selectable style={styles.title}>{variant === "home" ? "Next moves" : "Move the work"}</Text></View>
    <View accessible accessibilityLabel="Session-only build queue. Reload clears changes. Nothing is saved, dispatched, executed, deployed, or promoted to canon." style={styles.truth}><Text selectable style={styles.truthTitle}>SESSION QUEUE · NOT DISPATCHED</Text><Text selectable style={styles.truthBody}>Reload clears additions, priority changes, and status changes. DONE LOCAL is metadata only, not execution or verification.</Text></View>
    {variant === "build" ? <View style={styles.addCard}><Text accessibilityRole="header" selectable style={styles.addTitle}>Add a local move</Text><TextInput accessibilityHint="The title stays in this app session and is not dispatched." accessibilityLabel="New session build move" maxLength={120} onChangeText={setDraft} onSubmitEditing={addMove} placeholder="What should move next?" placeholderTextColor="#8EA0B7" style={styles.input} value={draft}/><Text selectable style={styles.controlLabel}>NEW MOVE PRIORITY</Text><View style={styles.priorityRow}>{BUILD_QUEUE_PRIORITIES.map((value)=><PriorityButton id="new move" key={value} onSelect={setPriority} priority={value} selected={priority===value}/>)}</View><Pressable accessibilityHint="Adds only to this app session. Does not save or dispatch." accessibilityLabel="Add move to session build queue" accessibilityRole="button" accessibilityState={{disabled:addDisabled}} disabled={addDisabled} onPress={addMove} style={({pressed})=>[styles.addAction,addDisabled&&styles.disabled,pressed&&styles.pressed]}><Text style={styles.addActionText}>Add to session queue</Text></Pressable></View> : null}
    <Text accessibilityLiveRegion="polite" selectable style={styles.summary}>{visible.length} visible · {queue.totalCount} session moves · {queue.activeCount} active local · {queue.doneCount} done local</Text>
    {visible.map((item,index)=><View key={item.id} style={[styles.task,item.status==="DONE_LOCAL"&&styles.done]}>
      <View style={styles.taskHeader}><Text selectable style={styles.position}>{String(index+1).padStart(2,"0")}</Text><View style={styles.taskCopy}><Text accessibilityRole="header" selectable style={styles.taskTitle}>{item.title}</Text><Text selectable style={styles.area}>{item.area}</Text></View></View>
      <View accessible accessibilityLabel={`Priority ${PRIORITY_LABELS[item.priority]}. Status ${item.status}.`} style={styles.states}><Text selectable style={styles.chip}>PRIORITY {PRIORITY_LABELS[item.priority]}</Text><Text selectable style={styles.chip}>STATUS {item.status.replaceAll("_"," ")}</Text></View>
      {variant === "build" ? <><Text selectable style={styles.controlLabel}>SET PRIORITY</Text><View style={styles.priorityRow}>{BUILD_QUEUE_PRIORITIES.map((value)=><PriorityButton id={item.id} key={value} onSelect={(next)=>onReprioritize(item.id,next)} priority={value} selected={item.priority===value}/>)}</View></> : null}
      <Pressable accessibilityHint="Changes only local session metadata. Does not save or dispatch." accessibilityLabel={`Advance local status for ${item.id}`} accessibilityRole="button" disabled={item.status==="DONE_LOCAL"} onPress={()=>onAdvance(item.id)} style={({pressed})=>[styles.statusAction,item.status==="DONE_LOCAL"&&styles.disabled,pressed&&styles.pressed]}><Text selectable style={styles.statusText}>{item.status==="QUEUED"?"Mark active locally":item.status==="ACTIVE_LOCAL"?"Mark done locally":"Done locally"}</Text></Pressable>
    </View>)}
  </View>;
}

const styles=StyleSheet.create({
  container:{width:"100%"}, heading:{marginBottom:12,marginTop:28}, eyebrow:{color:"#52D3FF",fontSize:10,fontWeight:"900",letterSpacing:1.4}, title:{color:"#F4F7FB",fontSize:22,fontWeight:"800",marginTop:6}, truth:{backgroundColor:"#122338",borderColor:"#405875",borderRadius:14,borderWidth:1,padding:13}, truthTitle:{color:"#57E39B",fontSize:10,fontWeight:"900"}, truthBody:{color:"#C4D0DF",fontSize:12,lineHeight:18,marginTop:5}, addCard:{backgroundColor:"#0D1A2A",borderColor:"#20344C",borderRadius:18,borderWidth:1,marginTop:12,padding:14}, addTitle:{color:"#F4F7FB",fontSize:17,fontWeight:"800"}, input:{backgroundColor:"#07111D",borderColor:"#405875",borderRadius:12,borderWidth:1,color:"#F4F7FB",fontSize:16,marginTop:12,minHeight:48,paddingHorizontal:12,paddingVertical:11}, controlLabel:{color:"#8EA0B7",fontSize:10,fontWeight:"900",marginTop:14}, priorityRow:{flexDirection:"row",flexWrap:"wrap",marginHorizontal:-4,marginTop:3}, priorityButton:{alignItems:"center",backgroundColor:"#101F31",borderColor:"#30465F",borderRadius:11,borderWidth:1,flexBasis:78,flexGrow:1,justifyContent:"center",marginHorizontal:4,marginTop:8,minHeight:48,paddingHorizontal:8,paddingVertical:10}, prioritySelected:{backgroundColor:"#16364C",borderColor:"#52D3FF",borderWidth:2}, priorityText:{color:"#AFC0D4",fontSize:10,fontWeight:"800",textAlign:"center"}, priorityTextSelected:{color:"#F4F7FB"}, addAction:{alignItems:"center",backgroundColor:"#52D3FF",borderRadius:12,justifyContent:"center",marginTop:14,minHeight:48,padding:12}, addActionText:{color:"#05101A",fontSize:13,fontWeight:"900"}, disabled:{opacity:.35}, pressed:{opacity:.76}, summary:{color:"#8EA0B7",fontSize:12,marginBottom:9,marginTop:14}, task:{width:"100%",backgroundColor:"#0D1A2A",borderColor:"#20344C",borderRadius:18,borderWidth:1,marginBottom:11,padding:14}, done:{borderColor:"#35664E",opacity:.78}, taskHeader:{alignItems:"flex-start",flexDirection:"row"}, position:{color:"#52D3FF",fontSize:12,fontWeight:"900",marginRight:11}, taskCopy:{flex:1,minWidth:0}, taskTitle:{color:"#F4F7FB",fontSize:15,fontWeight:"700",lineHeight:21}, area:{color:"#8EA0B7",fontSize:10,marginTop:5,textTransform:"uppercase"}, states:{flexDirection:"row",flexWrap:"wrap",marginHorizontal:-3,marginTop:8}, chip:{backgroundColor:"#15263A",borderColor:"#405875",borderRadius:999,borderWidth:1,color:"#D8E3F1",fontSize:9,fontWeight:"900",marginHorizontal:3,marginTop:6,paddingHorizontal:8,paddingVertical:6}, statusAction:{alignItems:"center",borderColor:"#405875",borderRadius:11,borderWidth:1,justifyContent:"center",marginTop:12,minHeight:48,padding:10}, statusText:{color:"#F4F7FB",fontSize:12,fontWeight:"800"}
});
