import { Pressable, StyleSheet, Text, View } from "react-native";
import type { FieldBriefBlockReasonCode, FieldBriefItem, FieldBriefSection, FieldBriefSession, FieldBriefView } from "../data/fieldBrief";

const BLOCK_REASON_COPY:Readonly<Record<FieldBriefBlockReasonCode,string>>=Object.freeze({
 INVALID_CHECK_TIME:"Brief and source clocks do not match.",INPUT_SCHEMA_INVALID:"Source metadata shape is invalid.",INPUT_EFFECT_CLAIM:"Source metadata claims a forbidden effect.",DUPLICATE_SOURCE_ID:"Source IDs are not unique.",DAILY_MISSION_BLOCKED:"Daily Mission is blocked.",BUILD_IDENTITY_UNBOUND:"Build identity is not CI-bound.",BUILD_IDENTITY_MISMATCH:"Build and promotion evidence SHAs do not match.",STALE_EVIDENCE:"Evidence is stale.",FUTURE_EVIDENCE:"Evidence is future-dated.",INVALID_EVIDENCE:"Evidence metadata is invalid.",UNAVAILABLE_EVIDENCE:"Evidence is unavailable.",PROMOTION_UNBOUND:"Promotion readiness is unbound."
});
const EMPTY_COPY:Readonly<Record<FieldBriefSection,string>>=Object.freeze({NOW:"NO NOW BRIEF ITEMS",NEXT:"NO NEXT BRIEF ITEMS",WATCH:"NO WATCH BRIEF ITEMS",GATE:"NO GATE BRIEF ITEMS"});
function MetadataRow({label,value}:Readonly<{label:string;value:string}>){return <View accessible accessibilityLabel={`${label}: ${value}`} style={styles.metadataRow}><Text selectable style={styles.metadataLabel}>{label}</Text><Text selectable style={styles.metadataValue}>{value}</Text></View>;}
function BriefItemCard({focused,item,reviewed,onReview}:Readonly<{focused:boolean;item:FieldBriefItem;reviewed:boolean;onReview:(itemId:string)=>void}>){return <View accessible={false} style={[styles.item,focused&&styles.itemFocused]} testID={`field-brief-item-${item.id}`}>
 <View style={styles.itemHeader}><Text selectable style={styles.rank}>{item.section} · {String(item.rank).padStart(2,"0")}</Text><Text selectable style={styles.reasonCode}>{item.reasonCode}</Text></View>
 <Text accessibilityRole="header" selectable style={styles.itemTitle}>{item.title}</Text>
 <Text selectable style={styles.reasonCopy}>{item.reasonCode}</Text>
 <View accessible accessibilityLabel={reviewed?"SESSION REVIEWED. NOT EXECUTED.":"NOT REVIEWED. NOT EXECUTED."} style={styles.reviewState}><Text selectable style={styles.reviewStateText}>{reviewed?"SESSION REVIEWED · NOT EXECUTED":"NOT REVIEWED · NOT EXECUTED"}</Text></View>
 {focused?<View accessible accessibilityLabel="SESSION FOCUS. NOT EXECUTION." style={styles.focusState}><Text selectable style={styles.focusStateText}>SESSION FOCUS · NOT EXECUTION</Text></View>:null}
 <View style={styles.itemMetadata}><MetadataRow label="SOURCE" value={`${item.sourceKind} · ${item.sourceId}`}/><MetadataRow label="ITEM ID" value={item.id}/><MetadataRow label="TRUTH" value={item.truth}/><MetadataRow label="PERSISTENCE / TRANSPORT" value={`${item.persistence} · ${item.transport}`}/></View>
 <Pressable accessibilityHint="Records session-only review. It does not execute or change inputs, save, or send." accessibilityLabel={`Review advisory item ${item.id}`} accessibilityRole="button" accessibilityState={{disabled:reviewed,selected:reviewed}} disabled={reviewed} hitSlop={4} onPress={()=>onReview(item.id)} style={({pressed})=>[styles.reviewAction,reviewed&&styles.actionDisabled,pressed&&!reviewed&&styles.pressed]}><Text selectable style={styles.actionText}>{reviewed?"Reviewed in this session":"Review advisory item"}</Text></Pressable>
 </View>;}
function BriefSection({focusedItemId,items,reviewedItemIds,section,onReview}:Readonly<{focusedItemId:string|null;items:readonly FieldBriefItem[];reviewedItemIds:readonly string[];section:FieldBriefSection;onReview:(itemId:string)=>void}>){return <View accessible={false} style={styles.section} testID={`field-brief-section-${section.toLowerCase()}`}><Text accessibilityRole="header" selectable style={styles.sectionTitle}>{section}</Text>{items.length===0?<View accessible accessibilityLabel={`${section}: no field-brief items. No work was executed.`} style={styles.emptySection}><Text selectable style={styles.emptySectionTitle}>{EMPTY_COPY[section]}</Text><Text selectable style={styles.emptySectionCopy}>No work was executed.</Text></View>:items.map((item)=><BriefItemCard focused={focusedItemId===item.id} item={item} key={item.id} onReview={onReview} reviewed={reviewedItemIds.includes(item.id)}/>)}</View>;}
export function FieldBriefCard({session,view,onAdvanceFocus,onReview}:Readonly<{session:FieldBriefSession;view:FieldBriefView;onAdvanceFocus:()=>void;onReview:(itemId:string)=>void}>){const blocked=view.state==="BLOCKED",noItems=view.allItems.length===0;return <View accessible={false} style={styles.card} testID="field-brief-card">
 <Text selectable style={styles.eyebrow}>FIELD BRIEF</Text><Text accessibilityRole="header" selectable style={styles.title}>Phone-ready advisory</Text>
 <View accessible accessibilityLabel={`Field brief state: ${blocked?"BLOCKED. ADVISORY NOT LIVE.":"READY. ADVISORY NOT LIVE."} ${view.truth}`} accessibilityLiveRegion="polite" style={[styles.summary,blocked?styles.summaryBlocked:styles.summaryReady]} testID="field-brief-summary"><Text selectable style={[styles.summaryState,blocked?styles.summaryStateBlocked:styles.summaryStateReady]}>{blocked?"BLOCKED · ADVISORY NOT LIVE":"READY · ADVISORY NOT LIVE"}</Text><Text selectable style={styles.summaryTruth}>{view.truth} · LIVE FALSE</Text><Text selectable style={styles.summaryTime}>CREATED {view.createdAt??"UNAVAILABLE"}</Text></View>
 <View accessible accessibilityLabel="OFFLINE-SAFE REVIEW. Session review does not save, send, execute, approve, or promote." style={styles.offlineTruth}><Text selectable style={styles.offlineTruthTitle}>OFFLINE-SAFE REVIEW</Text><Text selectable style={styles.offlineTruthCopy}>Session-only review does not save, send, execute, approve, or promote.</Text></View>
 <View accessible accessibilityLabel="HUMAN GATE REQUIRED. No approval has been recorded." style={styles.humanGate}><Text selectable style={styles.humanGateTitle}>HUMAN GATE REQUIRED</Text><Text selectable style={styles.humanGateCopy}>No approval has been recorded.</Text></View>
 <View style={styles.provenance}><MetadataRow label="VIEW IDENTITY" value={view.identityKey}/><MetadataRow label="BUILD SHA" value={view.buildSha??"UNBOUND"}/><MetadataRow label="EVIDENCE OBSERVED" value={view.evidenceObservedAt??"UNAVAILABLE"}/></View>
 {view.blockReasonCodes.length>0?<View style={styles.blockReasons}><Text accessibilityRole="header" selectable style={styles.blockHeading}>BLOCKED REASONS</Text>{view.blockReasonCodes.map((code,index)=><View accessible accessibilityLabel={`Blocked reason ${index+1}, ${code}: ${BLOCK_REASON_COPY[code]}`} key={code} style={styles.blockReason}><Text selectable style={styles.blockCode}>{String(index+1).padStart(2,"0")} · {code}</Text><Text selectable style={styles.blockCopy}>{BLOCK_REASON_COPY[code]}</Text></View>)}</View>:null}
 {noItems?<View accessible accessibilityLabel="NO FIELD BRIEF ITEMS. No work was executed." style={styles.emptyBrief}><Text selectable style={styles.emptyBriefTitle}>NO FIELD BRIEF ITEMS</Text><Text selectable style={styles.emptyBriefCopy}>The canonical view supplied no advisory item. No work was executed.</Text></View>:<><BriefSection focusedItemId={session.focusedItemId} items={view.now} onReview={onReview} reviewedItemIds={session.reviewedItemIds} section="NOW"/><BriefSection focusedItemId={session.focusedItemId} items={view.next} onReview={onReview} reviewedItemIds={session.reviewedItemIds} section="NEXT"/><BriefSection focusedItemId={session.focusedItemId} items={view.watch} onReview={onReview} reviewedItemIds={session.reviewedItemIds} section="WATCH"/><BriefSection focusedItemId={session.focusedItemId} items={view.gate} onReview={onReview} reviewedItemIds={session.reviewedItemIds} section="GATE"/><Pressable accessibilityHint="Moves session-only focus to the next field-brief item. It does not execute or change inputs." accessibilityLabel="Focus next field-brief item" accessibilityRole="button" accessibilityState={{disabled:noItems}} disabled={noItems} hitSlop={4} onPress={onAdvanceFocus} style={({pressed})=>[styles.focusAction,pressed&&styles.pressed]}><Text selectable style={styles.actionText}>Focus next field-brief item</Text></Pressable></>}
 <View style={styles.sessionTruth}><MetadataRow label="SESSION TRUTH" value={session.truth}/><MetadataRow label="SESSION VIEW IDENTITY" value={session.viewIdentityKey}/><MetadataRow label="PERSISTENCE / TRANSPORT" value={`${session.persistence} · ${session.transport}`}/><MetadataRow label="FOCUSED ITEM" value={session.focusedItemId??"NONE"}/></View>
 <Text selectable style={styles.boundary}>Offline-safe metadata only. No work was executed, saved, sent, approved, merged, deployed, delivered, hosted, or promoted to canon.</Text>
 </View>;}
const styles=StyleSheet.create({
 card:{width:"100%",minWidth:0,backgroundColor:"#0D1A2A",borderColor:"#20344C",borderRadius:20,borderWidth:1,marginTop:14,padding:16},eyebrow:{color:"#52D3FF",fontSize:10,fontWeight:"900",letterSpacing:1.2},title:{color:"#F4F7FB",fontSize:22,fontWeight:"800",lineHeight:29,marginTop:5},summary:{minWidth:0,borderRadius:14,borderWidth:1,marginTop:14,padding:12},summaryReady:{backgroundColor:"#142F24",borderColor:"#397857"},summaryBlocked:{backgroundColor:"#342320",borderColor:"#935C52"},summaryState:{fontSize:11,fontWeight:"900",letterSpacing:.7},summaryStateReady:{color:"#8EE4B5"},summaryStateBlocked:{color:"#FFB7AD"},summaryTruth:{color:"#C4D0DF",fontSize:10,lineHeight:16,marginTop:6},summaryTime:{color:"#8EA0B7",fontSize:9,lineHeight:15,marginTop:5},
 offlineTruth:{backgroundColor:"#122338",borderColor:"#405875",borderRadius:14,borderWidth:1,marginTop:10,padding:12},offlineTruthTitle:{color:"#52D3FF",fontSize:10,fontWeight:"900",letterSpacing:.7},offlineTruthCopy:{color:"#F4F7FB",fontSize:11,lineHeight:17,marginTop:5},humanGate:{backgroundColor:"#271F32",borderColor:"#765A91",borderRadius:14,borderWidth:1,marginTop:10,padding:12},humanGateTitle:{color:"#D9B8FA",fontSize:11,fontWeight:"900",letterSpacing:.7},humanGateCopy:{color:"#F4F7FB",fontSize:12,lineHeight:18,marginTop:5},provenance:{minWidth:0,backgroundColor:"#07111D",borderColor:"#20344C",borderRadius:14,borderWidth:1,marginTop:10,paddingHorizontal:12},metadataRow:{minWidth:0,borderBottomColor:"#20344C",borderBottomWidth:StyleSheet.hairlineWidth,paddingVertical:9},metadataLabel:{color:"#8EA0B7",fontSize:9,fontWeight:"900",letterSpacing:.7},metadataValue:{color:"#52D3FF",fontSize:10,lineHeight:16,marginTop:3},
 blockReasons:{width:"100%",minWidth:0},blockHeading:{color:"#D9E4F2",fontSize:11,fontWeight:"900",letterSpacing:.8,marginTop:18},blockReason:{minWidth:0,backgroundColor:"#342320",borderColor:"#935C52",borderRadius:13,borderWidth:1,marginTop:8,padding:11},blockCode:{color:"#FFB7AD",fontSize:9,fontWeight:"900",lineHeight:15},blockCopy:{color:"#F4F7FB",fontSize:11,lineHeight:17,marginTop:5},emptyBrief:{minWidth:0,backgroundColor:"#172232",borderColor:"#46566D",borderRadius:14,borderStyle:"dashed",borderWidth:1,marginTop:14,padding:12},emptyBriefTitle:{color:"#D9E4F2",fontSize:11,fontWeight:"900"},emptyBriefCopy:{color:"#AFC0D4",fontSize:11,lineHeight:17,marginTop:5},
 section:{width:"100%",minWidth:0,marginTop:18},sectionTitle:{color:"#52D3FF",fontSize:12,fontWeight:"900",letterSpacing:1},emptySection:{minWidth:0,backgroundColor:"#172232",borderColor:"#46566D",borderRadius:12,borderStyle:"dashed",borderWidth:1,marginTop:8,padding:11},emptySectionTitle:{color:"#AFC0D4",fontSize:10,fontWeight:"900"},emptySectionCopy:{color:"#AFC0D4",fontSize:10,lineHeight:16,marginTop:4},item:{width:"100%",minWidth:0,backgroundColor:"#07111D",borderColor:"#405875",borderRadius:14,borderWidth:1,marginTop:8,padding:12},itemFocused:{borderColor:"#D9B8FA",borderWidth:2},itemHeader:{alignItems:"flex-start",flexDirection:"row",flexWrap:"wrap",justifyContent:"space-between"},rank:{color:"#8EA0B7",fontSize:9,fontWeight:"900"},reasonCode:{color:"#52D3FF",fontSize:9,fontWeight:"900",lineHeight:15},itemTitle:{color:"#F4F7FB",fontSize:15,fontWeight:"800",lineHeight:21,marginTop:8},reasonCopy:{color:"#C4D0DF",fontSize:11,lineHeight:17,marginTop:5},reviewState:{backgroundColor:"#172232",borderRadius:999,marginTop:10,paddingHorizontal:9,paddingVertical:6},reviewStateText:{color:"#D9E4F2",fontSize:9,fontWeight:"900"},focusState:{backgroundColor:"#271F32",borderRadius:999,marginTop:6,paddingHorizontal:9,paddingVertical:6},focusStateText:{color:"#D9B8FA",fontSize:9,fontWeight:"900"},itemMetadata:{minWidth:0,marginTop:4},reviewAction:{alignItems:"center",borderColor:"#405875",borderRadius:12,borderWidth:1,justifyContent:"center",marginTop:10,minHeight:48,paddingHorizontal:12,paddingVertical:11},focusAction:{alignItems:"center",backgroundColor:"#271F32",borderColor:"#765A91",borderRadius:12,borderWidth:1,justifyContent:"center",marginTop:14,minHeight:48,paddingHorizontal:12,paddingVertical:11},actionDisabled:{opacity:.5},pressed:{opacity:.76},actionText:{color:"#F4F7FB",fontSize:12,fontWeight:"800",textAlign:"center"},sessionTruth:{minWidth:0,backgroundColor:"#122338",borderColor:"#405875",borderRadius:14,borderWidth:1,marginTop:14,paddingHorizontal:12},boundary:{color:"#AFC0D4",fontSize:11,lineHeight:17,marginTop:14,textAlign:"center"}
});
