import { StyleSheet, Text, View } from "react-native";
import type { PromotionReadinessView } from "../data/promotionReadiness";

type ReasonCode=PromotionReadinessView["reasonCodes"][number];
const REASON_COPY:Readonly<Record<ReasonCode,string>>=Object.freeze({EVIDENCE_EFFECT_CLAIM:"BLOCKED — Evidence claims an effect that is not allowed.",EVIDENCE_BOUNDARY_INVALID:"BLOCKED — Evidence boundary metadata is invalid.",CURRENT_BUILD_UNBOUND:"BLOCKED — Current build has no immutable SHA.",EVIDENCE_BUILD_UNBOUND:"BLOCKED — Evidence bundle has no immutable build SHA.",BUILD_SHA_MISMATCH:"EVIDENCE MISMATCH — Current and evidence build SHAs differ.",EVALUATION_TIME_INVALID:"BLOCKED — Readiness evaluation time is invalid.",EVIDENCE_TIME_INVALID:"BLOCKED — Evidence observation time is invalid.",EVIDENCE_FUTURE:"BLOCKED — Evidence is dated in the future.",EVIDENCE_STALE:"STALE EVIDENCE — Evidence is outside the accepted freshness window.",HUMAN_APPROVAL_REQUIRED:"HUMAN GATE REQUIRED — No approval has been recorded."});
function MetadataRow({label,value}:Readonly<{label:string;value:string}>){return <View accessible accessibilityLabel={label+": "+value} style={styles.metadataRow}><Text selectable style={styles.metadataLabel}>{label}</Text><Text selectable style={styles.metadataValue}>{value}</Text></View>;}
export function PromotionReadinessCard({view}:Readonly<{view:PromotionReadinessView}>){const ready=view.state==="READY_FOR_HUMAN_REVIEW",readinessLabel=ready?"READY FOR HUMAN REVIEW":"NOT READY FOR HUMAN REVIEW";return (
 <View accessible={false} style={styles.card} testID="promotion-readiness-card">
  <Text selectable style={styles.eyebrow}>PROMOTION READINESS</Text><Text accessibilityRole="header" selectable style={styles.title}>Evidence before authority</Text>
  <View accessible accessibilityLabel={readinessLabel+". HUMAN GATE REQUIRED. "+view.truth+"."} accessibilityLiveRegion="polite" style={[styles.status,ready?styles.ready:styles.notReady]}><Text selectable style={styles.statusLabel}>{readinessLabel}</Text><Text selectable style={styles.copy}>{view.truth}</Text></View>
  <View accessible accessibilityLabel="HUMAN GATE REQUIRED. No approval has been recorded. No merge, deployment, delivery, or canon promotion occurred." style={styles.gate}><Text selectable style={styles.gateTitle}>HUMAN GATE REQUIRED</Text><Text selectable style={styles.body}>No approval has been recorded.</Text><Text selectable style={styles.copy}>No merge, deployment, delivery, or canon promotion occurred.</Text></View>
  <Text accessibilityRole="header" selectable style={styles.section}>ORDERED CRITERIA</Text>
  {view.criteria.map((item,index)=><View accessible accessibilityLabel={"Criterion "+(index+1)+", "+item.id+". "+item.state+". "+item.label+". "+item.detail} key={item.id} style={[styles.item,item.state==="PASS"?styles.pass:item.state==="BLOCK"?styles.block:styles.pending]}><Text selectable style={styles.code}>{String(index+1).padStart(2,"0")+" · "+item.state+" · "+item.id}</Text><Text selectable style={styles.body}>{item.label}</Text><Text selectable style={styles.copy}>{item.detail}</Text></View>)}
  <Text accessibilityRole="header" selectable style={styles.section}>ORDERED REASONS</Text>
  {view.reasonCodes.length===0?<View style={styles.item}><Text selectable style={styles.body}>NO EVIDENCE REASONS</Text><Text selectable style={styles.copy}>Readiness still does not constitute approval.</Text></View>:view.reasonCodes.map((code,index)=><View accessible accessibilityLabel={"Reason "+(index+1)+", "+code+": "+REASON_COPY[code]} key={code} style={styles.reason}><Text selectable style={styles.code}>{"REASON "+String(index+1).padStart(2,"0")+" · "+code}</Text><Text selectable style={styles.body}>{REASON_COPY[code]}</Text></View>)}
  <Text accessibilityRole="header" selectable style={styles.section}>SELECTABLE IMMUTABLE METADATA</Text>
  <View style={styles.metadata}><MetadataRow label="REPOSITORY" value={view.repository}/><MetadataRow label="EVIDENCE BUNDLE" value={view.evidenceBundleId??"UNAVAILABLE"}/><MetadataRow label="EVIDENCE SOURCE SHA" value={view.evidenceSourceSha??"UNAVAILABLE"}/><MetadataRow label="EVIDENCE BUILD SHA" value={view.evidenceBuildSha??"UNBOUND"}/><MetadataRow label="CURRENT BUILD SHA" value={view.currentBuildSha??"UNBOUND"}/><MetadataRow label="EVIDENCE AGE" value={view.evidenceAgeDays===null?"UNAVAILABLE":view.evidenceAgeDays+" DAYS"}/><MetadataRow label="APPROVAL STATE" value={view.approvalState}/></View>
  <View accessible accessibilityLabel={"Next human action: "+view.nextActionLabel+". This card cannot approve, merge, deploy, send, or promote canon."} style={styles.next}><Text selectable style={styles.gateTitle}>NEXT HUMAN ACTION</Text><Text selectable style={styles.body}>{view.nextActionLabel}</Text><Text selectable style={styles.copy}>This read-only card cannot approve, merge, deploy, send, or promote canon.</Text></View>
 </View>);}
const styles=StyleSheet.create({card:{width:"100%",minWidth:0,backgroundColor:"#0D1A2A",borderColor:"#20344C",borderRadius:20,borderWidth:1,marginTop:12,padding:16},eyebrow:{color:"#52D3FF",fontSize:10,fontWeight:"900",letterSpacing:1.2},title:{color:"#F4F7FB",fontSize:21,fontWeight:"800",marginTop:5},status:{borderRadius:14,borderWidth:1,marginTop:14,padding:13},ready:{backgroundColor:"#142F24",borderColor:"#397857"},notReady:{backgroundColor:"#342A1D",borderColor:"#9B7438"},statusLabel:{color:"#F4F7FB",fontSize:12,fontWeight:"900"},gate:{backgroundColor:"#271F32",borderColor:"#765A91",borderRadius:14,borderWidth:1,marginTop:10,padding:13},gateTitle:{color:"#D9B8FA",fontSize:11,fontWeight:"900"},section:{color:"#D9E4F2",fontSize:11,fontWeight:"900",marginTop:20},item:{width:"100%",minWidth:0,borderRadius:13,borderWidth:1,marginTop:8,padding:12},pass:{backgroundColor:"#132B21",borderColor:"#356E50"},block:{backgroundColor:"#342320",borderColor:"#935C52"},pending:{backgroundColor:"#342A1D",borderColor:"#8B6A36"},reason:{width:"100%",minWidth:0,backgroundColor:"#07111D",borderColor:"#405875",borderRadius:13,borderWidth:1,marginTop:8,padding:12},code:{color:"#52D3FF",fontSize:9,fontWeight:"900",lineHeight:15},body:{color:"#F4F7FB",fontSize:13,fontWeight:"800",lineHeight:19,marginTop:5},copy:{color:"#C4D0DF",fontSize:11,lineHeight:17,marginTop:5},metadata:{minWidth:0,backgroundColor:"#07111D",borderColor:"#20344C",borderRadius:14,borderWidth:1,marginTop:8,paddingHorizontal:12},metadataRow:{minWidth:0,borderBottomColor:"#20344C",borderBottomWidth:StyleSheet.hairlineWidth,paddingVertical:10},metadataLabel:{color:"#8EA0B7",fontSize:9,fontWeight:"900"},metadataValue:{color:"#52D3FF",fontSize:10,lineHeight:16,marginTop:4},next:{backgroundColor:"#122338",borderColor:"#405875",borderRadius:13,borderWidth:1,marginTop:14,padding:12}});
