import { StyleSheet, Text, View } from "react-native";
import type { ConsolidatedCycleReceipt,CycleVerificationState } from "../data/consolidatedCycleReceipt";
import type { ResilienceFreshnessState,ResilienceFreshnessView } from "../data/resilienceFreshness";
type Props=Readonly<{freshness:ResilienceFreshnessView;loading?:boolean;receipt:ConsolidatedCycleReceipt|null}>;
const SUMMARY=Object.freeze({ALL_CYCLES_EVIDENCE_VERIFIED:"All listed cycles contain verified repository evidence.",PARTIAL_OR_UNVERIFIED:"One or more cycles remain partial or unverified.",FAILED_EVIDENCE:"One or more cycles contain failed verification evidence.",EMPTY:"NO RECEIPT EVIDENCE"});
const FRESH:Readonly<Record<ResilienceFreshnessState,string>>=Object.freeze({CURRENT:"CURRENT — Evidence observation is inside the current freshness window.",AGING:"AGING — Evidence is approaching its freshness boundary.",STALE:"STALE — Evidence is outside the accepted freshness window.",UNAVAILABLE:"UNAVAILABLE — No evidence observation timestamp is available.",INVALID:"INVALID — Evidence observation time could not be validated.",FUTURE:"FUTURE — Evidence observation time is dated after the injected evaluation time."});
function visible(state:CycleVerificationState,conclusion:string|null):CycleVerificationState{return state==="VERIFIED"&&conclusion?.toLowerCase()!=="success"?"UNVERIFIED":state;}
function Unavailable({label,detail}:Readonly<{label:string;detail:string}>){return <View accessible accessibilityLabel={label+". "+detail} accessibilityLiveRegion="polite" style={styles.unavailable}><Text selectable style={styles.body}>{label}</Text><Text selectable style={styles.copy}>{detail}</Text></View>;}
export function ReceiptTimelineCard({freshness,loading=false,receipt}:Props){if(loading)return <View style={styles.card}><Text selectable style={styles.eyebrow}>C7–C12 RECEIPT TIMELINE</Text><Text accessibilityRole="header" selectable style={styles.title}>Repository evidence history</Text><Unavailable label="LOADING RECEIPT EVIDENCE" detail="No verification result is available yet. Nothing is treated as verified."/></View>;if(receipt===null)return <View style={styles.card}><Text selectable style={styles.eyebrow}>C7–C12 RECEIPT TIMELINE</Text><Text accessibilityRole="header" selectable style={styles.title}>Repository evidence history</Text><Unavailable label="RECEIPT EVIDENCE UNAVAILABLE" detail="No cycle is treated as verified."/></View>;return <View accessible={false} style={styles.card} testID="receipt-timeline-card">
<Text selectable style={styles.eyebrow}>C7–C12 RECEIPT TIMELINE</Text><Text accessibilityRole="header" selectable style={styles.title}>Repository evidence history</Text><Text selectable style={styles.readOnly}>RECEIPT EVIDENCE · READ ONLY</Text>
<View accessible accessibilityLabel={"Receipt summary: "+receipt.summaryState+". "+SUMMARY[receipt.summaryState]} accessibilityLiveRegion="polite" style={styles.summary}><Text selectable style={styles.body}>{receipt.summaryState}</Text><Text selectable style={styles.copy}>{SUMMARY[receipt.summaryState]}</Text><Text selectable style={styles.counts}>{"TOTAL "+receipt.totalCycles+" · VERIFIED "+receipt.verifiedCycles+" · PARTIAL "+receipt.partialCycles+" · FAILED "+receipt.failedCycles+" · UNVERIFIED "+receipt.unverifiedCycles}</Text></View>
<View accessible accessibilityLabel={"Evidence freshness: "+FRESH[freshness.state]+" Reason: "+freshness.reasonCode} accessibilityLiveRegion="polite" style={styles.summary}><Text selectable style={styles.section}>EVIDENCE FRESHNESS</Text><Text selectable style={styles.body}>{freshness.state}</Text><Text selectable style={styles.copy}>{FRESH[freshness.state]}</Text><Text selectable style={styles.metadata}>{"OBSERVED "+(freshness.observedAt??"UNAVAILABLE")+"\nCHECKED "+(freshness.checkedAt??"UNAVAILABLE")+"\nAGE "+(freshness.ageDays===null?"UNAVAILABLE":freshness.ageDays+" DAYS")+"\nNEXT BOUNDARY "+(freshness.nextBoundaryAt??"UNAVAILABLE")+"\nREASON "+freshness.reasonCode}</Text><Text selectable style={styles.truth}>{freshness.truth} · LIVE FALSE</Text></View>
<Text accessibilityRole="header" selectable style={styles.section}>ORDERED CYCLE EVIDENCE</Text>
{receipt.cycles.length===0?<Unavailable label="NO RECEIPT EVIDENCE" detail="The canonical receipt contains no C7–C12 cycle entries."/>:receipt.cycles.map(entry=>{const state=visible(entry.verificationState,entry.verificationRunConclusion);return <View accessible accessibilityLabel={entry.cycle+", "+state+", checkpoint "+entry.checkpointSha} key={entry.cycle} style={styles.cycle}><Text accessibilityRole="header" selectable style={styles.cycleTitle}>{entry.cycle+" · "+state}</Text><Text selectable style={styles.metadata}>{"CHECKPOINT SHA\n"+entry.checkpointSha+"\nPACKETS\n"+entry.packetIds.join("\n")+"\nVERIFIED AT\n"+(entry.verifiedAt??"NOT VERIFIED")+"\nRUN EVIDENCE\n"+(entry.verificationRunId===null?"NO VERIFIED RUN":entry.verificationRunId+" · "+(entry.verificationRunConclusion??"UNAVAILABLE"))}</Text></View>;})}
<Text selectable style={styles.truth}>{receipt.truth} · {receipt.storageScope} · {receipt.transport}</Text><Text selectable style={styles.boundary}>No merge, deployment, delivery, hosting, or canon promotion is proven.</Text></View>;}
const styles=StyleSheet.create({card:{width:"100%",minWidth:0,backgroundColor:"#0D1A2A",borderColor:"#20344C",borderRadius:20,borderWidth:1,marginTop:12,padding:16},eyebrow:{color:"#52D3FF",fontSize:10,fontWeight:"900",letterSpacing:1.2},title:{color:"#F4F7FB",fontSize:21,fontWeight:"800",lineHeight:28,marginTop:5},readOnly:{color:"#D9B8FA",fontSize:10,fontWeight:"900",marginTop:10},summary:{minWidth:0,backgroundColor:"#122338",borderColor:"#405875",borderRadius:14,borderWidth:1,marginTop:12,padding:12},section:{color:"#D9E4F2",fontSize:11,fontWeight:"900",marginTop:20},body:{color:"#F4F7FB",fontSize:12,fontWeight:"900"},copy:{color:"#C4D0DF",fontSize:11,lineHeight:17,marginTop:5},counts:{color:"#D9E4F2",fontSize:9,lineHeight:16,marginTop:8},metadata:{minWidth:0,color:"#52D3FF",fontSize:10,lineHeight:16,marginTop:8},truth:{color:"#AFC0D4",fontSize:10,lineHeight:16,marginTop:12},unavailable:{minWidth:0,backgroundColor:"#172232",borderColor:"#46566D",borderRadius:14,borderStyle:"dashed",borderWidth:1,marginTop:12,padding:12},cycle:{width:"100%",minWidth:0,backgroundColor:"#172232",borderColor:"#46566D",borderRadius:14,borderWidth:1,marginTop:8,padding:12},cycleTitle:{color:"#F4F7FB",fontSize:15,fontWeight:"900"},boundary:{color:"#AFC0D4",fontSize:11,lineHeight:17,marginTop:14,textAlign:"center"}});
